<template>
<svg
    width="40"
    height="40"
    viewBox="0 0 24 24"
  >
    <line
      fill="none"
      stroke="#fff"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="2"
      x1="12"
      x2="12"
      y1="19"
      y2="5"
    />

    <line
      fill="none"
      stroke="#fff"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="2"
      x1="5"
      x2="19"
      y1="12"
      y2="12"
    />
  </svg>
</template>
